### PR TITLE
188 add navigation query string flag options

### PR DESCRIPTION
**Pull request by StianSto**
heres hoping i understood the assignment correctly. I assumed this issue's purpose was to add a functionality to share a link to students, teachers etc, but limit what they can see and navigate through.  

I added a functionality to the nav that renders the nav differently depending on the nav query. 
example: ?nav=programme will render the closest parent with a type of programme, and its children. 
if no nav param is present it defaults to only show the current page and its children.

### CODE REVIEW

**Review by Fermain — COMMENTED** [review]
I haven't tested, the code looks good but I wonder if the responsibility for detecting the querystring should live in layout so that it can be passed down to any prop in the tree if needed for future?

**Review by pretzL — COMMENTED** [review]
I agree with Oliver. The code looks good, but to avoid future cases where we're all fetching the URL path from different components, let's move it to the base layout to utilize, alternatively a store.

**Comment by StianSto** [comment]
update: added a context that can be used in the tree. some funny monkeybusiness happened when i tried to use props bubbling down. +layout now takes care of setting the "render by type"

**Review by Fermain — APPROVED** [review]
Tested, working well - exactly what we need

**Pull request merged**
