### PR TITLE
Molly: sanitise user input & Auto resize textarea

### PR DESCRIPTION
**Pull request by MegumiKim**
Following changes are made in this PR:

- Add DOMPurify to user input to prevent XXS and reinforce security
- Add autoresize feature to chat box textarea
- Add Molly icon to Molly's response

### CODE REVIEW

**Review by Melisa-Zorraindo — APPROVED** [review]
We can maybe install the dependency's types by running `npm i --save-dev @types/dompurify` ?

Great job!

**Comment by MegumiKim** [comment]
Thanks @Melisa-Zorraindo! 
As suggested @types added!

**Comment by MegumiKim** [comment]
Last commit fixed a bug which enabled empty query to be sent.

**Comment by MegumiKim** [comment]
Spoke with Melisa about stress test of user input sanitisation.

I have tested with some basic XXS and DOMPurify has successfully removed malicious code before being sent to the server. 
Nevertheless I have created a separate issue for future sprint to run some thorough vulnerability test on Molly chat.

**Pull request merged**
