### PR TITLE
move nav button and search to the right of header

### PR DESCRIPTION
**Pull request by MegumiKim**
Moved the hamburger menu/nav icon to the right of the header.

While doing so, I thought that the placement of search icon/search bar was rather strange (in the middle). So I tucked it into the right side together with the hamburger. Please let me know if it's no good.

### CODE REVIEW

**Comment by Fermain** [comment]
Can you post a screenshot of how this change looks?

**Comment by MegumiKim** [comment]
Sure. 
Screenshot 2023-10-04 at 10 41 51
Screenshot 2023-10-04 at 10 41 04

**Comment by pretzL** [comment]
I'm personally more a fan of the centered search bar. Makes it feel more accessible to a certain degree, and more visible.

**Comment by MegumiKim** [comment]
No Problem. I put back the Search in the middle as it was before.

**Review by Fermain — APPROVED** [review]

**Pull request merged**
