### PR TITLE
Reset scroll position on navigate

### LINKED ISSUE #112: Navigating to a new lesson persists scroll
When viewing a lesson, if you scroll down the page and then navigate to a new lesson, your scroll state persists. Scroll height should likely be reset when navigating to a new lesson.

### PR DESCRIPTION
**Pull request by Fermain**

### CODE REVIEW

**Review by Melisa-Zorraindo — APPROVED** [review]
I encounter an error in the console that I couldn't figure out the solution to. However, the code works fine despite the error.

**Comment by Fermain** [comment]
> I encounter an error in the console that I couldn't figure out the solution to. However, the code works fine despite the error.

What does it say?

**Comment by Melisa-Zorraindo** [comment]
```
Main.svelte?t=1689782991113:181 Uncaught (in promise) TypeError: main?.scrollToTop is not a function
    at Main.svelte?t=1689782991113:181:9
    at client.js?v=a583b5cb:466:44
    at Array.forEach (<anonymous>)
    at initialize (client.js?v=a583b5cb:466:28)
    at Object._hydrate (client.js?v=a583b5cb:1795:4)
    at async Module.start (start.js:22:3)
```

**Comment by Anclagen** [comment]
I get the pretty much the same error but it seems to be working fine.

**Pull request merged**
